name: Terraform CI-CD 
on:
  push:
    branches:
     - main 
jobs:
  terraform-ci-cd:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint. 
    permissions:
      id-token: write 
      contents: read
    steps:
      - name: Download repo and cd to the repo folder
        uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::213911150042:role/deployment-role
          aws-region: eu-central-1 
      - name: test aws access
        run: aws sts get-caller-identity
