name: Terraform CI
on:
  push:
    branches:
     - main 
jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint. 
    permissions:
      id-token: write 
      contents: read
    steps:
      - uses: hashicorp/setup-terraform@v2
